package main.java.com.mealforks.thelastknight.game;

public enum GameSprite {
    PLAYER_FACING_UP,
    PLAYER_FACING_DOWN,
    PLAYER_FACING_RIGHT,
    PLAYER_FACING_LEFT,
    TRADER,
    ENEMY,
    GIFT_CHARACTER,
    TEXT_ONLY,
    DOOR_KEY,
    HEALTH_POTION,
    LUCK_AMULET,
    STRENGTH_AMULET,
    WOODEN_SWORD,
    IRON_SWORD,
    INFERNAL_SWORD,
    WOODEN_WAND,
    CRYSTAL_WAND,
    CELESTIAL_WAND,
    LEATHER_ARMOR,
    IRON_ARMOR,
    NONE
}
